import type { Metadata } from "next";
import localFont from "next/font/local";
import { SimpuProvider } from "@simpu/inbox-sdk";
import "./globals.css";
import { Nav } from "@/components/layout/nav";
import { QueryClientProvider } from "@tanstack/react-query";
import { Provider } from "@/components/provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <SimpuProvider
            colorPalette="green"
            organisationID="c91740d3988211eba1bb86d35ec4f76b"
            accessToken="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzQ5NjA1NDIsImlhdCI6MTczMjM2ODU0Miwic3ViIjoiMDZkNDcwNDdlM2EyMTFlYTkzNzA4NmQzNWVjNGY3NmIifQ.9tCz-q1rDKzgEdAVPOIkO9WDlM16H4bRu_S6scRoKpA"
          >
            <div className="flex h-screen w-full overflow-y-hidden">
              <Nav />
              {children}
            </div>
          </SimpuProvider>
        </Provider>
      </body>
    </html>
  );
}
